
package service.business;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArticleImpleService", targetNamespace = "http://business.service/", wsdlLocation = "http://localhost:8080/vente_hebillement_WS/venteHabillemntArticle?wsdl")
public class ArticleImpleService
    extends Service
{

    private final static URL ARTICLEIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException ARTICLEIMPLESERVICE_EXCEPTION;
    private final static QName ARTICLEIMPLESERVICE_QNAME = new QName("http://business.service/", "ArticleImpleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/vente_hebillement_WS/venteHabillemntArticle?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARTICLEIMPLESERVICE_WSDL_LOCATION = url;
        ARTICLEIMPLESERVICE_EXCEPTION = e;
    }

    public ArticleImpleService() {
        super(__getWsdlLocation(), ARTICLEIMPLESERVICE_QNAME);
    }

    public ArticleImpleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARTICLEIMPLESERVICE_QNAME, features);
    }

    public ArticleImpleService(URL wsdlLocation) {
        super(wsdlLocation, ARTICLEIMPLESERVICE_QNAME);
    }

    public ArticleImpleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARTICLEIMPLESERVICE_QNAME, features);
    }

    public ArticleImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArticleImpleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IArticle
     */
    @WebEndpoint(name = "ArticleImplePort")
    public IArticle getArticleImplePort() {
        return super.getPort(new QName("http://business.service/", "ArticleImplePort"), IArticle.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IArticle
     */
    @WebEndpoint(name = "ArticleImplePort")
    public IArticle getArticleImplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business.service/", "ArticleImplePort"), IArticle.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARTICLEIMPLESERVICE_EXCEPTION!= null) {
            throw ARTICLEIMPLESERVICE_EXCEPTION;
        }
        return ARTICLEIMPLESERVICE_WSDL_LOCATION;
    }

}
