
package service.business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IArticle", targetNamespace = "http://business.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IArticle {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "annulerVente", targetNamespace = "http://business.service/", className = "service.business.AnnulerVente")
    @ResponseWrapper(localName = "annulerVenteResponse", targetNamespace = "http://business.service/", className = "service.business.AnnulerVenteResponse")
    @Action(input = "http://business.service/IArticle/annulerVenteRequest", output = "http://business.service/IArticle/annulerVenteResponse")
    public boolean annulerVente(
        @WebParam(name = "arg0", targetNamespace = "")
        Vente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addVersement", targetNamespace = "http://business.service/", className = "service.business.AddVersement")
    @ResponseWrapper(localName = "addVersementResponse", targetNamespace = "http://business.service/", className = "service.business.AddVersementResponse")
    @Action(input = "http://business.service/IArticle/addVersementRequest", output = "http://business.service/IArticle/addVersementResponse")
    public boolean addVersement(
        @WebParam(name = "arg0", targetNamespace = "")
        Versement arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.business.Achat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAchatBymotcle", targetNamespace = "http://business.service/", className = "service.business.GetAchatBymotcle")
    @ResponseWrapper(localName = "getAchatBymotcleResponse", targetNamespace = "http://business.service/", className = "service.business.GetAchatBymotcleResponse")
    @Action(input = "http://business.service/IArticle/getAchatBymotcleRequest", output = "http://business.service/IArticle/getAchatBymotcleResponse")
    public List<Achat> getAchatBymotcle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echangerVente", targetNamespace = "http://business.service/", className = "service.business.EchangerVente")
    @ResponseWrapper(localName = "echangerVenteResponse", targetNamespace = "http://business.service/", className = "service.business.EchangerVenteResponse")
    @Action(input = "http://business.service/IArticle/echangerVenteRequest", output = "http://business.service/IArticle/echangerVenteResponse")
    public boolean echangerVente(
        @WebParam(name = "arg0", targetNamespace = "")
        Vente arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Vente arg1);

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNeededArticle", targetNamespace = "http://business.service/", className = "service.business.GetNeededArticle")
    @ResponseWrapper(localName = "getNeededArticleResponse", targetNamespace = "http://business.service/", className = "service.business.GetNeededArticleResponse")
    @Action(input = "http://business.service/IArticle/getNeededArticleRequest", output = "http://business.service/IArticle/getNeededArticleResponse")
    public List<Article> getNeededArticle();

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Achat>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAchats", targetNamespace = "http://business.service/", className = "service.business.GetAllAchats")
    @ResponseWrapper(localName = "getAllAchatsResponse", targetNamespace = "http://business.service/", className = "service.business.GetAllAchatsResponse")
    @Action(input = "http://business.service/IArticle/getAllAchatsRequest", output = "http://business.service/IArticle/getAllAchatsResponse")
    public List<Achat> getAllAchats();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.business.Vente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVenteBymotcle", targetNamespace = "http://business.service/", className = "service.business.GetVenteBymotcle")
    @ResponseWrapper(localName = "getVenteBymotcleResponse", targetNamespace = "http://business.service/", className = "service.business.GetVenteBymotcleResponse")
    @Action(input = "http://business.service/IArticle/getVenteBymotcleRequest", output = "http://business.service/IArticle/getVenteBymotcleResponse")
    public List<Vente> getVenteBymotcle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllArticles", targetNamespace = "http://business.service/", className = "service.business.GetAllArticles")
    @ResponseWrapper(localName = "getAllArticlesResponse", targetNamespace = "http://business.service/", className = "service.business.GetAllArticlesResponse")
    @Action(input = "http://business.service/IArticle/getAllArticlesRequest", output = "http://business.service/IArticle/getAllArticlesResponse")
    public List<Article> getAllArticles();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCredit", targetNamespace = "http://business.service/", className = "service.business.AddCredit")
    @ResponseWrapper(localName = "addCreditResponse", targetNamespace = "http://business.service/", className = "service.business.AddCreditResponse")
    @Action(input = "http://business.service/IArticle/addCreditRequest", output = "http://business.service/IArticle/addCreditResponse")
    public int addCredit(
        @WebParam(name = "arg0", targetNamespace = "")
        Credit arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.business.Vente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addVente", targetNamespace = "http://business.service/", className = "service.business.AddVente")
    @ResponseWrapper(localName = "addVenteResponse", targetNamespace = "http://business.service/", className = "service.business.AddVenteResponse")
    @Action(input = "http://business.service/IArticle/addVenteRequest", output = "http://business.service/IArticle/addVenteResponse")
    public Vente addVente(
        @WebParam(name = "arg0", targetNamespace = "")
        Vente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.business.Article
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addArticle", targetNamespace = "http://business.service/", className = "service.business.AddArticle")
    @ResponseWrapper(localName = "addArticleResponse", targetNamespace = "http://business.service/", className = "service.business.AddArticleResponse")
    @Action(input = "http://business.service/IArticle/addArticleRequest", output = "http://business.service/IArticle/addArticleResponse")
    public Article addArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        Article arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.business.Achat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAchat", targetNamespace = "http://business.service/", className = "service.business.AddAchat")
    @ResponseWrapper(localName = "addAchatResponse", targetNamespace = "http://business.service/", className = "service.business.AddAchatResponse")
    @Action(input = "http://business.service/IArticle/addAchatRequest", output = "http://business.service/IArticle/addAchatResponse")
    public Achat addAchat(
        @WebParam(name = "arg0", targetNamespace = "")
        Achat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://business.service/", className = "service.business.DeleteArticle")
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://business.service/", className = "service.business.DeleteArticleResponse")
    @Action(input = "http://business.service/IArticle/deleteArticleRequest", output = "http://business.service/IArticle/deleteArticleResponse")
    public boolean deleteArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.business.Article
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateArticle", targetNamespace = "http://business.service/", className = "service.business.UpdateArticle")
    @ResponseWrapper(localName = "updateArticleResponse", targetNamespace = "http://business.service/", className = "service.business.UpdateArticleResponse")
    @Action(input = "http://business.service/IArticle/updateArticleRequest", output = "http://business.service/IArticle/updateArticleResponse")
    public Article updateArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        Article arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Vente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllVents", targetNamespace = "http://business.service/", className = "service.business.GetAllVents")
    @ResponseWrapper(localName = "getAllVentsResponse", targetNamespace = "http://business.service/", className = "service.business.GetAllVentsResponse")
    @Action(input = "http://business.service/IArticle/getAllVentsRequest", output = "http://business.service/IArticle/getAllVentsResponse")
    public List<Vente> getAllVents();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.business.Article>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArticlesByMotcle", targetNamespace = "http://business.service/", className = "service.business.GetArticlesByMotcle")
    @ResponseWrapper(localName = "getArticlesByMotcleResponse", targetNamespace = "http://business.service/", className = "service.business.GetArticlesByMotcleResponse")
    @Action(input = "http://business.service/IArticle/getArticlesByMotcleRequest", output = "http://business.service/IArticle/getArticlesByMotcleResponse")
    public List<Article> getArticlesByMotcle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Vente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllVentsAvcCredit", targetNamespace = "http://business.service/", className = "service.business.GetAllVentsAvcCredit")
    @ResponseWrapper(localName = "getAllVentsAvcCreditResponse", targetNamespace = "http://business.service/", className = "service.business.GetAllVentsAvcCreditResponse")
    @Action(input = "http://business.service/IArticle/getAllVentsAvcCreditRequest", output = "http://business.service/IArticle/getAllVentsAvcCreditResponse")
    public List<Vente> getAllVentsAvcCredit();

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalCreditParClient", targetNamespace = "http://business.service/", className = "service.business.GetTotalCreditParClient")
    @ResponseWrapper(localName = "getTotalCreditParClientResponse", targetNamespace = "http://business.service/", className = "service.business.GetTotalCreditParClientResponse")
    @Action(input = "http://business.service/IArticle/getTotalCreditParClientRequest", output = "http://business.service/IArticle/getTotalCreditParClientResponse")
    public double getTotalCreditParClient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.business.Vente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllVentsOfAclient", targetNamespace = "http://business.service/", className = "service.business.GetAllVentsOfAclient")
    @ResponseWrapper(localName = "getAllVentsOfAclientResponse", targetNamespace = "http://business.service/", className = "service.business.GetAllVentsOfAclientResponse")
    @Action(input = "http://business.service/IArticle/getAllVentsOfAclientRequest", output = "http://business.service/IArticle/getAllVentsOfAclientResponse")
    public List<Vente> getAllVentsOfAclient(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.business.Credit>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCreditParCredit", targetNamespace = "http://business.service/", className = "service.business.GetAllCreditParCredit")
    @ResponseWrapper(localName = "getAllCreditParCreditResponse", targetNamespace = "http://business.service/", className = "service.business.GetAllCreditParCreditResponse")
    @Action(input = "http://business.service/IArticle/getAllCreditParCreditRequest", output = "http://business.service/IArticle/getAllCreditParCreditResponse")
    public List<Credit> getAllCreditParCredit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
