
package service.business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStatus", targetNamespace = "http://business.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IStatus {


    /**
     * 
     * @return
     *     returns java.util.List<service.business.Statistics>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVenteBymonths", targetNamespace = "http://business.service/", className = "service.business.GetVenteBymonths")
    @ResponseWrapper(localName = "getVenteBymonthsResponse", targetNamespace = "http://business.service/", className = "service.business.GetVenteBymonthsResponse")
    @Action(input = "http://business.service/IStatus/getVenteBymonthsRequest", output = "http://business.service/IStatus/getVenteBymonthsResponse")
    public List<Statistics> getVenteBymonths();

    /**
     * 
     * @return
     *     returns service.business.State
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppStatus", targetNamespace = "http://business.service/", className = "service.business.GetAppStatus")
    @ResponseWrapper(localName = "getAppStatusResponse", targetNamespace = "http://business.service/", className = "service.business.GetAppStatusResponse")
    @Action(input = "http://business.service/IStatus/getAppStatusRequest", output = "http://business.service/IStatus/getAppStatusResponse")
    public State getAppStatus();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.business.Statistics>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVenteCountByCategory", targetNamespace = "http://business.service/", className = "service.business.GetVenteCountByCategory")
    @ResponseWrapper(localName = "getVenteCountByCategoryResponse", targetNamespace = "http://business.service/", className = "service.business.GetVenteCountByCategoryResponse")
    @Action(input = "http://business.service/IStatus/getVenteCountByCategoryRequest", output = "http://business.service/IStatus/getVenteCountByCategoryResponse")
    public List<Statistics> getVenteCountByCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Statistics>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVenteCountByArticle", targetNamespace = "http://business.service/", className = "service.business.GetVenteCountByArticle")
    @ResponseWrapper(localName = "getVenteCountByArticleResponse", targetNamespace = "http://business.service/", className = "service.business.GetVenteCountByArticleResponse")
    @Action(input = "http://business.service/IStatus/getVenteCountByArticleRequest", output = "http://business.service/IStatus/getVenteCountByArticleResponse")
    public List<Statistics> getVenteCountByArticle();

    /**
     * 
     * @return
     *     returns java.util.List<service.business.Statistics>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVenteCountByTaille", targetNamespace = "http://business.service/", className = "service.business.GetVenteCountByTaille")
    @ResponseWrapper(localName = "getVenteCountByTailleResponse", targetNamespace = "http://business.service/", className = "service.business.GetVenteCountByTailleResponse")
    @Action(input = "http://business.service/IStatus/getVenteCountByTailleRequest", output = "http://business.service/IStatus/getVenteCountByTailleResponse")
    public List<Statistics> getVenteCountByTaille();

}
