
package service.business;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UserImpleService", targetNamespace = "http://business.service/", wsdlLocation = "http://localhost:8080/vente_hebillement_WS/venteHabillemnt?wsdl")
public class UserImpleService
    extends Service
{

    private final static URL USERIMPLESERVICE_WSDL_LOCATION;
    private final static WebServiceException USERIMPLESERVICE_EXCEPTION;
    private final static QName USERIMPLESERVICE_QNAME = new QName("http://business.service/", "UserImpleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/vente_hebillement_WS/venteHabillemnt?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERIMPLESERVICE_WSDL_LOCATION = url;
        USERIMPLESERVICE_EXCEPTION = e;
    }

    public UserImpleService() {
        super(__getWsdlLocation(), USERIMPLESERVICE_QNAME);
    }

    public UserImpleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERIMPLESERVICE_QNAME, features);
    }

    public UserImpleService(URL wsdlLocation) {
        super(wsdlLocation, USERIMPLESERVICE_QNAME);
    }

    public UserImpleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERIMPLESERVICE_QNAME, features);
    }

    public UserImpleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserImpleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUser
     */
    @WebEndpoint(name = "UserImplePort")
    public IUser getUserImplePort() {
        return super.getPort(new QName("http://business.service/", "UserImplePort"), IUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUser
     */
    @WebEndpoint(name = "UserImplePort")
    public IUser getUserImplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business.service/", "UserImplePort"), IUser.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERIMPLESERVICE_EXCEPTION!= null) {
            throw USERIMPLESERVICE_EXCEPTION;
        }
        return USERIMPLESERVICE_WSDL_LOCATION;
    }

}
